### ISSUE TITLE
Run Sql Script on Azure stopped working after Azure PowerShell modules update

### ISSUE THREAD

**Issue by arnodekok** [crimdon/SQLToolkitAzure#23]
We recently updated our Azure PowerShell modules to version 6.6.0
After the update our pipelines with the 'Run Sql Script on Azure' task stopped working.

Error message:

2018-08-06T12:31:13.0707471Z ##[error]System.ArgumentException: Please provide a valid tenant or a valid subscription.
2018-08-06T12:31:13.0716934Z    at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.SetCurrentContext(String subscriptionNameOrId, String tenantId, String name)
2018-08-06T12:31:13.0717383Z    at Microsoft.Azure.Commands.Profile.SetAzureRMContextCommand.<>c__DisplayClass37_1.<ExecuteCmdlet>b__2(AzureRmProfile profile, RMProfileClient client, String name)
2018-08-06T12:31:13.0717746Z    at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)
2018-08-06T12:31:13.0718091Z    at Microsoft.Azure.Commands.Profile.SetAzureRMContextCommand.SetContextWithOverwritePrompt(Action`3 setContextAction)
2018-08-06T12:31:13.0718409Z    at Microsoft.Azure.Commands.Profile.SetAzureRMContextCommand.ExecuteCmdlet()
2018-08-06T12:31:13.0718696Z    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
2018-08-06T12:31:13.3075134Z Running Script
2018-08-06T12:31:13.3075537Z 
2018-08-06T12:31:13.3076845Z 
2018-08-06T12:31:13.5873576Z Error running SQL script: Exception calling "Open" with "0" argument(s): "Login failed for user '*********'."
2018-08-06T12:31:13.5874037Z 
2018-08-06T12:31:13.5874282Z 
2018-08-06T12:31:13.5902824Z ##[error]System.Management.Automation.MethodInvocationException: Exception calling "Open" with "0" argument(s): "Login failed for user '********'." ---> System.Data.SqlClient.SqlException: Login failed for user '********'.
2018-08-06T12:31:13.5904881Z    at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
2018-08-06T12:31:13.5906802Z    at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
2018-08-06T12:31:13.5907441Z    at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
2018-08-06T12:31:13.5907975Z    at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
2018-08-06T12:31:13.5908461Z    at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
2018-08-06T12:31:13.5909032Z    at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
2018-08-06T12:31:13.5909613Z    at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
2018-08-06T12:31:13.5910157Z    at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
2018-08-06T12:31:13.5910754Z    at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
2018-08-06T12:31:13.5911220Z    at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
2018-08-06T12:31:13.5911561Z    at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
2018-08-06T12:31:13.5912039Z    at System.Data.SqlClient.SqlConnection.Open()
2018-08-06T12:31:13.5912329Z    at CallSite.Target(Closure , CallSite , Object )
2018-08-06T12:31:13.5912633Z    --- End of inner exception stack trace ---
2018-08-06T12:31:13.5912985Z    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2018-08-06T12:31:13.5913394Z    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2018-08-06T12:31:13.5913780Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2018-08-06T12:31:13.5914158Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2018-08-06T12:31:13.6155958Z ##[error]PowerShell script completed with 2 errors.

**Comment by crimdon** [comment]
May be a breaking change in there. Out of interest what version did you upgrade from?

**Comment by crimdon** [comment]
This appears to be the problem:

2018-08-06T12:31:13.0707471Z ##[error]System.ArgumentException: Please provide a valid tenant or a valid subscription.

**Comment by arnodekok** [comment]
We updated from version 5.2.0 (January 2018)

**Comment by crimdon** [comment]
Do you use RM or classic on the Azure Connection type? I've had a look at the code and unless the method I'm using is completely broken now, it uses this connection to get the subscription etc.

**Comment by arnodekok** [comment]
We're using RM for our Azure Connnections.

**Comment by crimdon** [comment]
Do any of the other tasks work? Also are you using onsite TFS or VSTS?

**Comment by arnodekok** [comment]
We're using VSTS. Other tasks like deploying an ARM template work without any problems.

**Comment by crimdon** [comment]
I've updated the modules on that task to a later version. Please download and try it again.

**Comment by arnodekok** [comment]
Everything is running fine again! Thanks for your fast support.

**Comment by crimdon** [comment]
Thats good news. I'll update the modules in the other tasks as well
