### ISSUE TITLE
PSInvalidOperationException: Run Login-AzureRmAccount to login

### ISSUE THREAD

**Issue by azizalibasic** [crimdon/SQLToolkitAzure#8]
I am getting the following error when attempting to run a file from the file system against an Azure Sql instance. I have triple checked the password and username.

```
2016-10-17T21:59:04.3790324Z ##[error]System.Management.Automation.PSInvalidOperationException: Run Login-AzureRmAccount to login.
2016-10-17T21:59:04.3790324Z    at Microsoft.Azure.Commands.ResourceManager.Common.AzureRMCmdlet.get_DefaultContext()
2016-10-17T21:59:04.3790324Z    at Microsoft.Azure.Commands.ResourceManager.Common.AzureRMCmdlet.LogCmdletStartInvocationInfo()
2016-10-17T21:59:04.3790324Z    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.BeginProcessing()
2016-10-17T21:59:04.3790324Z    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.BeginProcessing()
2016-10-17T21:59:04.3790324Z --- End of stack trace from previous location where exception was thrown ---
2016-10-17T21:59:04.3790324Z    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.HandleException(ExceptionDispatchInfo capturedException)
2016-10-17T21:59:04.3790324Z    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.BeginProcessing()
2016-10-17T21:59:04.3790324Z    at System.Management.Automation.Cmdlet.DoBeginProcessing()
2016-10-17T21:59:04.3790324Z    at System.Management.Automation.CommandProcessorBase.DoBegin()
2016-10-17T21:59:04.3910304Z ##[error]PowerShell script completed with 1 errors.
```

**Comment by crimdon** [comment]
That looks like your service endpoint isn't setup correctly so its never getting as far as running the script in the task. Remember you have you use a domain account when connecting the endpoint as it won't accept hotmail accounts.

**Comment by azizalibasic** [comment]
When you say domain account does this mean the account that I would use to connect to SQL azure via SQL server mgmt studio?

**Comment by crimdon** [comment]
Have a look at the link below. It explains how to setup an Azure Endpoint in TFS. None of the Azure tasks will work unless this Endpoint is in place

[https://blogs.msdn.microsoft.com/tfssetup/2016/04/01/build-and-deploy-azure-web-apps-using-team-foundation-serverservices-vnext-builds/](url)

**Comment by azizalibasic** [comment]
@crimdon I have this account setup correctly. I am able to deploy to my web app. I just cannot run sql scripts. What are your thoughts?

**Comment by crimdon** [comment]
Here is a copy of the logs I get when I run the task:

2016-07-21T14:23:46.0259134Z Running Stored Procedure  dbo.test  on Database  Test
2016-07-21T14:23:46.0259134Z Logging on to server  sqlcrimdon
2016-07-21T14:24:01.1039126Z Environment           : AzureCloud
2016-07-21T14:24:01.1049142Z Account               : tfsagent@crimdonhotmail.onmicrosoft.com
2016-07-21T14:24:01.1059131Z TenantId              : c8cdfde2-f79c-4261-a2da-45d237053ac3
2016-07-21T14:24:01.1069125Z SubscriptionId        : dcdf311e-79cf-4f82-968e-bd44a64f7ea6
2016-07-21T14:24:01.1069125Z CurrentStorageAccount : 
2016-07-21T14:24:01.1109129Z Finding Resource Group
2016-07-21T14:24:02.4107196Z Creating Firewall Rule
2016-07-21T14:24:06.9987963Z ResourceGroupName : WestEurope-PayAsYouGo
2016-07-21T14:24:06.9987963Z ServerName        : sqlcrimdon
2016-07-21T14:24:06.9997961Z StartIpAddress    : 104.214.231.187
2016-07-21T14:24:06.9997961Z EndIpAddress      : 104.214.231.187
2016-07-21T14:24:07.0007963Z FirewallRuleName  : TFSAgent

The tfsagent@crimdonhotmail.onmicrosoft.com account is the one I use when creating the endpoint. I created this in the Azure domain that was created for me when I setup an Azure account. All of the connections to Azure are handled by the endpoint in TFS. In my task I only fire off a sql command from powershell using the credentials supplied.
The endpoint account needs admin permissions as it creates a firewall rule on the fly and then removes it after the task has completed.
I use a different account in the task to connect to the database (the same one I would use in SSMS).
